server:
  port: 8004

spring:
  application:
    name: nacos-spring-cloud-provider
  profiles:
    include: web
    active: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
